---
# ハイフンやコロンが含まれる文字列の場合はダブルクォーテーションで囲んでいます
version: '2'

volumes:
  mysql_data:
  postgres_data:

services:
  # mysql
  mysql:
    container_name: mydb
    image: "mysql:5.7"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "change_password"
      # MYSQL_DATABASE: "test_db" #サンプル作成SQL内で作成されるので不要
    networks:
      - im_net
      
  # PostgreSQL
  postgres:
    container_name: pgdb
    image: "postgres:9.6.6-alpine"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./postgres/init:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "change_password"
    networks:
      - im_net
      
  # web(php & apache)
  web:
    depends_on:
      - mysql
      - postgres
    container_name: web
    build:
        context: ./php-apache
    image: "sakadonohito/php71-apache:1.0"
    ports:
      - "10080:80"
    volumes:
      - "./php-apache/html:/var/www/html" #INTER-Mediatorディレクトリの1つ上位のディレクトリをWebのrootにしています
    environment:
      MYSQL_HOST: mydb
      POSTGRES_HOST: pgdb
    networks:
      - im_net

#NetWork Setting
networks: 
  im_net: 

